name: style check
on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: corrode
    runs-on: ubuntu-latest
    steps:
    - name: clippy
      run: cargo clippy --all --all-features --tests -- -D warnings
    - name: rustfmt
      run: cargo fmt --all -- --check
