name: style check
on:
  push:
    branches: [ main ]


jobs:
  clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run Clippy
        run: cargo clippy --all-targets -- -D warnings
  formatting:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - name: install rustfmt
        run: rustup component add rustfmt
      - name: Check formatting
        run: cargo fmt --all --check
      - name: Checkout code
        uses: actions/checkout@v3

      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
